### ISSUE TITLE
Some Federale light units have from helmet popping helmet

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-streamlined-heisting#14]
Hey!

I noticed when testing that some Federale light units have FBI helmets when you pop them. These include: SWAT Variant 2 (Shotgun) and Gensec Variant 1 and 2 (One with g36 and one with a shotgun)

I did a little digging and noticed that only the Federale units **not** included in Streamlined Heisting assets folder are affected
(Expect special units, they work fine). Also noticed that theyr counter parts in Payday2/characters dont include .unit files, which makes me suspect that the federales are somehow drawing from normal payday 2 unit pool in regard of helmets. But you dont have ene_city_swat_1, which is Federale gensec 1 counter part, which is also affected, so it doesent make sense in that regard.

Anyways, im sure you know how to fix the issue! Out of curiosity if you manage to fix it, i would like to know what was the issue was exacly and how you managed to fix it.

I did not have any other unit editing mods present, and removing Streamlined Heisting fixes the issue

Heres a screenshot of the comparisons (Left the wrong helmet and right the one that was supposed to pop):
![20210920215506_1](https://user-images.githubusercontent.com/32977052/134060508-7836ac7e-798b-4c84-aca1-b9cd9e3febb1.jpg)

Ben

**Comment by segabl** [comment]
This is easily explained, I only changed the units for the regular swat federales and did not touch any of the others (FBI, Gensec). Most of those draw their models from the swat units, thats why they appear to be changed, however their unit files are still vanilla and therefore drop their original helmets. Ingame this shouldn't be an issue since regardless of difficulty, only the swat faction enemies are spawned.

**Comment by sirben99** [comment]
Ohhhhh, i thought that they would spawn correcting to theyr difficulty. Is this ur change or is it in base game too?

**Comment by segabl** [comment]
it wouldn't break anything, just a matter of restoring the original unit category stuff. I did it just for the sake of saving me some work, since they all look the same anyways. I'm using the fbi ones for light units, while I have the regular swat just to set up the base and for use as the shield unit (since most enemies draw from that normal swat as their model base).

**Comment by sirben99** [comment]
Ah, where would i start changing the unit catecory stuff? Are Federales also the only units that use only one difficulty model, or do some other units do the same (Like Murkywater).

I also have couple of questions that i found confusing. If you prefer i asked somewhere else let me know!:

1. What does dyn_package="false"> in assets.xml mean? I cant load any DLC .unit files without it, otherwice theyr corrupt (Murkywater, Federales). I dint have to put it in vanilla changing unit mods. Should i put it to those too?

2. Some of the unit override mods use theyr own .unit and husk.unit files, is this breaking anything in Streamlined heisting? (E.g: Murkywater in Streamlined use Scar, while they dont in the override mod)

3. Apparently Federale FBI and Gensec Heavy units use the same model. Do you know is there a way to only make a override mod for Gensec and FBI seperatly, or is it impossible without adding new units?

**Comment by segabl** [comment]
Unit category stuff is set up in groupaitweakdata. I did the same thing for murkies (since they all use the same models too, or rather copy pasted models) and for the russian mercs (since they have incomplete factions and look very similar anyways).

For your questions:
1. This means that superblt will not immediately try and load added unit files, which should not be done when replacing existing units, since they're either already loaded or loaded by the game at some point anyways.
2. They might be overridden by SH if they are mod_overrides, if they are superblt mods, they will override SH if their mod priority is lower. unit files shouldn't be too much of an issue, however there's always a possibility of conflicts when one of the mods expects a vanilla material config or object for instance which is overriden by the other mod.
3. you don't have to add a new unit, since the unit is separate from the model. so they are different units, linking to the same model. how it works is the .unit file links and .object file which determines the model that is used. so in that case you would just have to make a new .object and .model file and change the path in the .unit to that new .object.

**Comment by sirben99** [comment]
Thank you for the answers! I have couple of questions/things i would like to discuss, so ill contact you in Discord regarding that, if i cant figure it out on my own.

You can close this and the other issue as you see fit
